MODEL:
  META_ARCHITECTURE: "Baseline1"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 11
DATASETS:
  TRAIN: ("bdd12k_action_train",)
  TEST: ("bdd12k_action_test",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 10000
OUTPUT_DIR: "./outputs/"
