MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 11
DATASETS:
  TRAIN: ("bdd100k_train",)
  TEST: ("bdd100k_val",)
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (80000, 100000)
  MAX_ITER: 120000
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 10000
OUTPUT_DIR: "/data6/SRIP19_SelfDriving/bdd100k/Outputs/pretrained/"
